local AddonName, Addon = ...
-- ============================================
-- GRIP-EMS PLUGIN HANDSHAKE (Tier 0..5)
-- Registers DummyAnalyzer as a reversibly-owned addon.
-- Source of truth: jesperlive.github.io/GRIP-EMS-PluginAPI/reference/ai-context/
local GetCharDB = Addon.GetCharDB
local DebugLog = Addon.DebugLog
local ExtractSpellName = Addon.ExtractSpellName
local ExtractSpellFromSeqLine = Addon.ExtractSpellFromSeqLine
local GenerateEMSImportString = Addon.GenerateEMSImportString
local Ems_Default = Addon.Ems_Default
local GetActionPrefix = Addon.GetActionPrefix

local EMS_PLUGIN_ID = "dummyanalyzer"
local EMS_PLUGIN_NAME = "DummyAnalyzer EMS Plugin"
local EMS_PLUGIN_VERSION = "2.2.0"
Addon.emsPluginHandle = nil  -- populated by RegisterPlugin; nil until handshake succeeds
local emsContextCache = "none"
local emsLoadoutDirty = false

local function Ems_BuildSequenceData(seqName, orderedSteps)
    -- orderedSteps: array of spell names (built by ParseSequenceLines at the Best/Next button click)
    -- Single EMS builder (SequenceBuilder.lua) owns every sequence field; this only stamps meta.
    local clean = {}
    if type(orderedSteps) == "table" then
        for _, s in ipairs(orderedSteps) do
            if type(s) == "string" and s ~= "" then clean[#clean + 1] = s end
        end
    end
    orderedSteps = clean
    local cfg = (GetCharDB()).settings or {}
    local dbX = GetCharDB()
    local storedMap = (Addon.bestSequence and Addon.bestSequence.interleaveMap) or (dbX.bestSequence and dbX.bestSequence.interleaveMap) or nil
    local sequence, intervalMap = Addon.BuildSequence(orderedSteps, cfg, storedMap)
    if not sequence then return nil, "no spells" end
    local valid, errs, warns = Addon.ValidateSequenceActions(sequence.versions and sequence.versions[1] and sequence.versions[1].actions)
    if errs and #errs > 0 then
        DebugLog("info", "ems", "EMS ValidateActions errors: " .. table.concat(errs, "; "))
    end
    if warns and #warns > 0 then
        DebugLog("info", "ems", "EMS ValidateActions warnings: " .. table.concat(warns, "; "))
    end
    local now = time()
    local actionCount = #(sequence.versions[1].actions or {})
    sequence.name = seqName
    sequence.createdAt = now
    sequence.updatedAt = now
    sequence.description = "Auto-generated by DummyAnalyzer heuristic (" .. tostring(actionCount) .. " steps, context=" .. tostring(emsContextCache) .. ")"
    return sequence
end

function Addon.Ems_EnsureHandle()
    if Addon.emsPluginHandle then return true end
    local API = GRIPEMS and GRIPEMS.API
    if not API then return false, "GRIPEMS.API not available" end
    if not API:RequireVersion(3) then return false, "EMS v3+ required" end
    local ok, handle = pcall(API.RegisterPlugin, API, EMS_PLUGIN_ID, {
        name = EMS_PLUGIN_NAME,
        version = EMS_PLUGIN_VERSION,
        OnEnable = DummyAnalyzer_EMS_OnEnable,
        OnDisable = DummyAnalyzer_EMS_OnDisable,
    })
    if ok and handle then
        Addon.emsPluginHandle = handle
        print("|cff33ff33[DummyAnalyzer EMS]|r Registered on-demand (id=" .. EMS_PLUGIN_ID .. ").")
        return true
    end
    return false, "RegisterPlugin failed: " .. tostring(handle)
end

function Addon.Ems_PushBestSequence(orderedSteps)
    if not Addon.emsPluginHandle then
        local ok, reason = Addon.Ems_EnsureHandle()
        if not ok then
            print("|cffff8844[DummyAnalyzer EMS]|r GRIP-EMS not ready: " .. tostring(reason) .. ". Reload after EMS is loaded.")
            return
        end
    end
    local ctx = emsContextCache or "none"
    local name = "DummyAnalyzer > Best (" .. ctx .. ")"
    local seqData = Ems_BuildSequenceData(name, orderedSteps)
    -- Try UpdateSequence first (overwrites existing), fall back to CreateSequence
    local ok, reason = Addon.emsPluginHandle:UpdateSequence(name, seqData)
    if ok then
        if Addon.debugMode then print("|cff33ff33[DummyAnalyzer EMS]|r UpdateSequence OK: " .. name) end
    else
        ok, reason = Addon.emsPluginHandle:CreateSequence(name, seqData)
        if not ok then
            return nil, reason
        end
    end
    Addon.emsLastPushedName = name
    return name
end

local function Ems_PushImportExportProviders()
    if not Addon.emsPluginHandle then return end
    -- Import provider: detects our compressed format header, decodes via GenerateEMSImportString pipeline
    local ok1, reason1 = Addon.emsPluginHandle:RegisterImportProvider({
        id = "dummyanalyzer_da01",
        name = "DummyAnalyzer !DA01!",
        Detect = function(_, text)
            return type(text) == "string" and text:sub(1, 6) == "!DA01!"
        end,
        Parse = function(_, text)
            if not C_EncodingUtil then return nil end
            local encoded = text:sub(7) or ""
            if encoded == "" then return nil end
            local okDec, decoded = pcall(C_EncodingUtil.DecodeBase64, encoded)
            if not okDec or type(decoded) ~= "string" then return nil end
            if C_EncodingUtil.DecompressString then
                local okDc, dc = pcall(C_EncodingUtil.DecompressString, decoded)
                if okDc and type(dc) == "string" then decoded = dc end
            end
            local ok, payload = pcall(C_EncodingUtil.DeserializeCBOR, decoded)
            if not ok or type(payload) ~= "table" then return nil end
            local seq = payload.sequence or payload.Sequences
            if type(seq) ~= "table" then return nil end
            -- Return the same shape S.Decode yields for a single sequence
            return { name = type(payload.name) == "string" and payload.name or "DummyAnalyzer Imported", sequence = seq }
        end,
    })
    if not ok1 and Addon.debugMode then
        print("|cffff8844[DummyAnalyzer EMS]|r ImportProvider registration failed: " .. tostring(reason1))
    end
    -- Export provider: invokes GenerateEMSImportString on a sequence name
    local ok2, reason2 = Addon.emsPluginHandle:RegisterExportProvider({
        id = "dummyanalyzer_da01",
        name = "DummyAnalyzer !DA01!",
        Serialize = function(_, seq)
            if type(seq) ~= "table" or type(seq.versions) ~= "table" then return "" end
            local v = seq.versions[seq.activeVersionIndex or seq.defaultVersion or 1]
            if type(v) ~= "table" then return "" end
            local castCounts, damageData, orderedSteps = {}, {}, {}
            local rawSteps = type(v.steps) == "table" and v.steps or {}
            if #rawSteps == 0 and type(v.actions) == "table" then
                for _, act in ipairs(v.actions) do
                    if type(act) == "table" and act.type == "action" then
                        local name = act.macro and ExtractSpellName(act.macro) or nil
                        if name and name ~= "" then rawSteps[#rawSteps + 1] = name end
                    end
                end
            end
            for _, step in ipairs(rawSteps) do
                local spellName = ExtractSpellName(step) or ExtractSpellFromSeqLine(step) or step
                if spellName and spellName ~= "" then
                    castCounts[spellName] = (castCounts[spellName] or 0) + 1
                    damageData[spellName] = { total = 0, hits = 0 }
                    local seen = false
                    for _, s in ipairs(orderedSteps) do
                        if s == spellName then seen = true; break end
                    end
                    if not seen then orderedSteps[#orderedSteps + 1] = spellName end
                end
            end
            if #orderedSteps == 0 then return "" end
            if C_EncodingUtil and GenerateEMSImportString then
                local ok3, s = pcall(GenerateEMSImportString, castCounts, damageData, orderedSteps)
                if ok3 and type(s) == "string" and s ~= "" then return s end
            end
            return "!DA01!export-error"
        end,
    })
    if not ok2 and Addon.debugMode then
        print("|cffff8844[DummyAnalyzer EMS]|r ExportProvider registration failed: " .. tostring(reason2))
    end
end

local function Ems_RegisterRegistries()
    if not Addon.emsPluginHandle then return end
    -- Variable provider: returns simcDeficit ratio per spell (non-secret scalar)
    Addon.emsPluginHandle:RegisterVariableProvider({
        id = "dummyanalyzer_simc_deficit",
        name = "DummyAnalyzer: SimC Deficit Ratio",
        Resolve = function(_, varName)
            if type(varName) ~= "string" then return nil end
            local spell = varName:match("^dummyanalyzer_simc_deficit%.(.+)$")
            if not spell then return nil end
            local db = GetCharDB and GetCharDB() or nil
            local cache = db and db.deficitCache
            if not cache or type(cache) ~= "table" then return 0 end
            return cache[spell] or 0
        end,
    })
    -- Step function: deficit-aware reorder. EMS passes us resolved step texts, we return them in
    -- a static order previously optimized by our hill-climber. Pure, no side effects.
    Addon.emsPluginHandle:RegisterStepFunction({
        id = "dummyanalyzer_deficit_order",
        name = "DummyAnalyzer: Deficit-Ordered",
        Expand = function(_, resolvedStepTexts)
            local steps = resolvedStepTexts or {}
            local function passthrough()
                local out = {}
                for i, t in ipairs(steps) do out[i] = t end
                return out
            end
            -- Ordering key must be the NON-deduplicated spell list. orderedSpellNames is
            -- deduped by ParseSequenceLines, so it cannot express "Kill Command at 1, 5, 9".
            -- fullSteps is one entry per macro line, in order. Addon.bestSequence is the
            -- freshest copy (restored from SavedVariables at load); fall back to the char DB.
            local best = Addon and Addon.bestSequence
            if not best then
                local db = GetCharDB and GetCharDB() or nil
                best = db and db.bestSequence or nil
            end
            local order = best and best.fullSteps
            if type(order) ~= "table" or #order == 0 then
                return passthrough()
            end
            -- EMS hands us resolved MACROTEXT, not spell names. Bucket each entry under the
            -- spell it casts so a spell appearing N times keeps all N of its entries.
            local buckets, bucketOrder = {}, {}
            for _, t in ipairs(steps) do
                local name = ExtractSpellFromSeqLine(t)
                if not name then
                    -- A step shape we do not understand. Never drop steps.
                    return passthrough()
                end
                if not buckets[name] then
                    buckets[name] = {}
                    bucketOrder[#bucketOrder + 1] = name
                end
                local b = buckets[name]
                b[#b + 1] = t
            end
            if #bucketOrder == 0 then
                return passthrough()
            end
            -- Emit in optimizer order, consuming one occurrence at a time.
            local out, taken = {}, {}
            for _, name in ipairs(order) do
                local b = buckets[name]
                if b then
                    local i = (taken[name] or 0) + 1
                    if b[i] then
                        taken[name] = i
                        out[#out + 1] = b[i]
                    end
                end
            end
            -- Append anything the optimizer never saw, in its original order.
            for _, name in ipairs(bucketOrder) do
                local b = buckets[name]
                for i = (taken[name] or 0) + 1, #b do
                    out[#out + 1] = b[i]
                end
            end
            if #out == 0 then
                return passthrough()
            end
            return out
        end,
    })
    -- Condition: "training-dummy log available" — true when we have at least 1 player log
    Addon.emsPluginHandle:RegisterCondition({
        id = "dummyanalyzer_has_log",
        name = "DummyAnalyzer: A real log exists",
        Evaluate = function()
            local db = GetCharDB and GetCharDB() or nil
            if not db or type(db.logs) ~= "table" then return false end
            for _, log in ipairs(db.logs) do
                if log and not log.isSimC and log.castCounts and next(log.castCounts) then
                    return true
                end
            end
            return false
        end,
    })
end

local function Ems_RegisterEvents()
    local API = GRIPEMS and GRIPEMS.API
    if not API then return end
    API:On("CONTEXT_CHANGED", function(newCtx, _oldCtx)
        emsContextCache = tostring(newCtx or "none")
    end)
    API:On("LOADOUT_CHANGED", function(_newID, _newName, _oldID, _oldName)
        emsLoadoutDirty = true
    end)
    API:On("SETTING_CHANGED", function(_key, _value) end)
    -- Tracks which sequence is actually executing. This is the public replacement for the old
    -- read of GRIPEMS.Engine._lastClickedSequence. Payload: (seqName, step, numSteps).
    API:On("SEQUENCE_STEP_ADVANCED", function(seqName)
        if type(seqName) == "string" and seqName ~= "" then
            Addon.lastActiveSequence = seqName
        end
    end)
    API:On("PLUGIN_SEQUENCES_LOADED", function()
        emsContextCache = tostring(API:GetCurrentContext() or "none")
    end)
    API:On("GEMS_UI_READY", function()
        if Addon.emsPluginHandle then
            Ems_PushImportExportProviders()
        end
    end)
end

-- (Ems_BuildOrderedFromSeqText and Ems_CacheOrdered removed: ParseSequenceLines + inline
--  assignment in Best/Next Seq handlers covers both roles.)

function DummyAnalyzer_EMS_OnEnable(handle)
    -- Save the handle so Push/Copy/etc work after reload (EMS calls OnEnable directly with the handle)
    if handle then Addon.emsPluginHandle = handle end
    Ems_RegisterRegistries()
    Ems_RegisterEvents()
    -- GEMS_UI_READY may have already fired before this plugin registered, in which case the
    -- event hook in Ems_RegisterEvents never runs and the providers are never registered.
    -- Call directly too; EMS rejects a duplicate id with (false, reason), which the callee
    -- already handles, so the double call is safe.
    Ems_PushImportExportProviders()
    -- Promote existing bestSequence into EMS if one is already persisted
    local db = GetCharDB()
    if db and db.bestSequence and type(db.bestSequence.seqText) == "string" and db.bestSequence.seqText ~= "" then
        -- fullSteps is the non-deduplicated step list; orderedSpellNames collapses repeats, so
        -- promoting from it would re-create "A B A C A B" in EMS as "A B C" after every reload.
        -- Fall back to orderedSpellNames only for SavedVariables written before fullSteps existed.
        local ordered = db.bestSequence.fullSteps
        if type(ordered) ~= "table" or #ordered == 0 then
            ordered = db.bestSequence.orderedSpellNames
        end
        if type(ordered) == "table" and #ordered > 0 then
            Addon.Ems_PushBestSequence(ordered)
        end
    end
    if Addon.debugMode then print("|cff33ff33[DummyAnalyzer EMS]|r Plugin enabled.") end
end

function DummyAnalyzer_EMS_OnDisable(_handle)
    -- EMS reverts our contributions automatically. Nothing to clean up here unless we want to.
    if Addon.debugMode then print("|cff33ff33[DummyAnalyzer EMS]|r Plugin disabled (contributions reverted by EMS).") end
end

local pluginInitFrame = CreateFrame("Frame")
pluginInitFrame:RegisterEvent("PLAYER_LOGIN")
pluginInitFrame:SetScript("OnEvent", function(_, event)
    if event ~= "PLAYER_LOGIN" then return end
    local API = GRIPEMS and GRIPEMS.API
    if not API then
        print("|cffff8844[DummyAnalyzer EMS]|r GRIPEMS.API not present - EMS not loaded.")
        return
    end
    if not API:RequireVersion(3) then
        print("|cffff8844[DummyAnalyzer EMS]|r EMS v3+ required for plugin support.")
        return
    end
    -- If we already have a handle, we're good
    if Addon.emsPluginHandle then
        print("|cff33ff33[DummyAnalyzer EMS]|r Already have plugin handle.")
        return
    end
    emsContextCache = "none"
    -- Try fresh registration
    Addon.emsPluginHandle = API:RegisterPlugin(EMS_PLUGIN_ID, {
        name = EMS_PLUGIN_NAME,
        version = EMS_PLUGIN_VERSION,
        OnEnable = DummyAnalyzer_EMS_OnEnable,
        OnDisable = DummyAnalyzer_EMS_OnDisable,
    })
    if Addon.emsPluginHandle then
        print("|cff33ff33[DummyAnalyzer EMS]|r Registered as '" .. EMS_PLUGIN_ID .. "' v" .. EMS_PLUGIN_VERSION)
        return
    end
    print("|cffff8844[DummyAnalyzer EMS]|r RegisterPlugin failed. Reload with GRIP-EMS loaded.")
end)

-- Fallback: if PLAYER_LOGIN missed (race condition), try again when EMS UI is ready
local uiReadyFrame = CreateFrame("Frame")
uiReadyFrame:RegisterEvent("ADDON_LOADED")
uiReadyFrame:SetScript("OnEvent", function(_, event, addonName)
    if event == "ADDON_LOADED" and addonName == "GRIP-EMS" then
        C_Timer.After(2, function()
            if not Addon.emsPluginHandle then
                local ok = Addon.Ems_EnsureHandle()
                if ok then
                    print("|cff33ff33[DummyAnalyzer EMS]|r Late registration via ADDON_LOADED fallback.")
                end
            end
        end)
    end
end)